# Module 14 - Domain-Based Feature Engineering

# 14. Domain-Based Feature Engineering

Domain chosen: Hotel Booking / Hospitality

Domain-based feature engineering means creating features using knowledge of how a particular business works.

In hotel booking data, useful features can be created from stay duration, guest information, booking details, pricing, and special requests.

For every feature, we will document:

- Feature Name
- Source Column(s)
- Logic
- Business Meaning
- ML Relevance
- Leakage Risk
- Retain or Remove

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    r"C:\Users\HP\Sprint_6_Feature_Engineering_-_Feature_Selection\data\hotel_bookings.csv"
)

df["children"] = df["children"].fillna(0)

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

### Observation

The Hotel Bookings dataset has been loaded and prepared for domain-based feature engineering.

The dataset contains booking, guest, stay, pricing, and reservation-related information that can be converted into meaningful hospitality features.

### Code Explanation

- `pd.read_csv()` loads the Hotel Bookings dataset.
- Missing values in `children` are treated as 0.
- The dataset is now ready for creating domain-specific features.

### Domain Thinking

A useful hotel feature should represent a meaningful aspect of a booking or guest behavior and should only use information available at the time the prediction is made.

### Feature 1: Total_Stay_Nights

Feature Name: Total_Stay_Nights

Source Columns: stays_in_weekend_nights, stays_in_week_nights

Logic: Add the number of weekend nights and weekday nights.

Business Meaning: Represents the complete duration of a guest's stay.

ML Relevance: Useful for understanding booking duration and predicting cancellation, demand, or booking value.

Leakage Risk: Low, because the planned stay duration is available from the booking information.

Retain or Remove: Retain, because it is a meaningful hotel-domain feature.

In [2]:
df["Total_Stay_Nights"] = (
    df["stays_in_weekend_nights"] +
    df["stays_in_week_nights"]
)

df[
    [
        "stays_in_weekend_nights",
        "stays_in_week_nights",
        "Total_Stay_Nights"
    ]
].head()

   stays_in_weekend_nights  stays_in_week_nights  Total_Stay_Nights
0                        0                     0                  0
1                        0                     0                  0
2                        0                     1                  1
3                        0                     1                  1
4                        0                     2                  2

### Observation

The two separate stay-duration columns have been combined into one meaningful feature, `Total_Stay_Nights`.

This feature gives a direct view of the total planned length of the hotel stay.

### Code Explanation

- `stays_in_weekend_nights` contains the number of weekend nights.
- `stays_in_week_nights` contains the number of weekday nights.
- Adding both columns creates `Total_Stay_Nights`.
- The feature is retained because it provides useful domain information without introducing post-outcome information.

### Feature 2: Total_Guests

Feature Name: Total_Guests

Source Columns: adults, children, babies

Logic: Add the number of adults, children, and babies in the booking.

Business Meaning: Represents the total number of guests included in a hotel booking.

ML Relevance: Useful for understanding booking size and guest composition. It can provide useful information for predicting cancellation, demand, or booking value.

Leakage Risk: Low, because guest counts are part of the booking information.

Retain or Remove: Retain, because it is a meaningful hospitality-domain feature.

In [3]:
df["Total_Guests"] = (
    df["adults"] +
    df["children"] +
    df["babies"]
)

df[
    [
        "adults",
        "children",
        "babies",
        "Total_Guests"
    ]
].head()

   adults  children  babies  Total_Guests
0       2       0.0       0           2.0
1       2       0.0       0           2.0
2       1       0.0       0           1.0
3       1       0.0       0           1.0
4       2       0.0       0           2.0

### Observation

The `adults`, `children`, and `babies` columns have been combined to create `Total_Guests`.

This feature gives a simple representation of the total number of guests included in each hotel booking.

### Code Explanation

- `adults` represents the number of adult guests.
- `children` represents the number of children.
- `babies` represents the number of babies.
- Adding these columns creates the `Total_Guests` feature.
- The feature is retained because guest count is an important part of hotel booking behavior.

### Feature 3: Total_Special_Requests

Feature Name: Total_Special_Requests

Source Columns: total_of_special_requests

Logic: Use the number of special requests made by the guest as the feature.

Business Meaning: Represents how many special requests are associated with the hotel booking.

ML Relevance: Special requests can provide information about guest preferences and booking behavior. This can be useful for predicting cancellation or other booking-related outcomes.

Leakage Risk: Low, provided the value is available at the time of prediction.

Retain or Remove: Retain, because it represents meaningful guest booking behavior.

In [4]:
df["Total_Special_Requests"] = df["total_of_special_requests"]

df[
    [
        "total_of_special_requests",
        "Total_Special_Requests"
    ]
].head()

   total_of_special_requests  Total_Special_Requests
0                          0                       0
1                          0                       0
2                          0                       0
3                          0                       0
4                          1                       1

### Observation

The `total_of_special_requests` column is represented as the domain-based feature `Total_Special_Requests`.

This feature captures the number of special requests associated with each booking.

### Code Explanation

- `total_of_special_requests` contains the number of special requests.
- The value is assigned to `Total_Special_Requests`.
- The feature is retained because it provides useful information about guest booking behavior.

### Feature 4: Is_Weekend_Stay

Feature Name: Is_Weekend_Stay

Source Columns: stays_in_weekend_nights

Logic: If the booking has one or more weekend nights, assign 1; otherwise assign 0.

Business Meaning: Indicates whether the guest's stay includes at least one weekend night.

ML Relevance: Weekend stays can represent different booking patterns and can help the model understand the timing of a hotel stay.

Leakage Risk: Low, because weekend-night information is part of the booking details.

Retain or Remove: Retain, because it converts stay information into a useful business indicator.

In [5]:
df["Is_Weekend_Stay"] = (
    df["stays_in_weekend_nights"] > 0
).astype(int)

df[
    [
        "stays_in_weekend_nights",
        "Is_Weekend_Stay"
    ]
].head()

   stays_in_weekend_nights  Is_Weekend_Stay
0                        0                0
1                        0                0
2                        0                0
3                        0                0
4                        0                0

### Observation

The `Is_Weekend_Stay` feature identifies whether a booking includes any weekend nights.

The feature contains:
- 1 → Booking includes a weekend stay
- 0 → Booking does not include a weekend stay

### Code Explanation

- `stays_in_weekend_nights > 0` checks whether at least one weekend night exists.
- `.astype(int)` converts the Boolean result into 1 and 0.
- The feature is retained because weekend stay information can help represent hotel booking patterns.

### Feature 5: Is_Long_Stay

Feature Name: Is_Long_Stay

Source Columns: Total_Stay_Nights

Logic: If the total stay is more than 7 nights, assign 1; otherwise assign 0.

Business Meaning: Indicates whether the booking represents a longer hotel stay.

ML Relevance: Long-stay bookings can have different booking patterns from short stays and may provide useful information for cancellation or demand-related models.

Leakage Risk: Low, because the feature is created from the planned stay duration.

Retain or Remove: Retain, because it converts stay duration into a simple business indicator.

In [6]:
df["Is_Long_Stay"] = (
    df["Total_Stay_Nights"] > 7
).astype(int)

df[
    [
        "Total_Stay_Nights",
        "Is_Long_Stay"
    ]
].head()

   Total_Stay_Nights  Is_Long_Stay
0                  0             0
1                  0             0
2                  1             0
3                  1             0
4                  2             0

### Observation

The `Is_Long_Stay` feature identifies bookings where the planned stay is more than 7 nights.

The feature contains:
- 1 → Long stay
- 0 → Not a long stay

### Code Explanation

- `Total_Stay_Nights > 7` checks whether the booking exceeds 7 nights.
- `.astype(int)` converts the Boolean result into 1 and 0.
- The feature is retained because it provides a simple representation of long-stay booking behavior.

### Feature 6: Booking_Lead_Category

Feature Name: Booking_Lead_Category

Source Columns: lead_time

Logic: Group the number of days between booking and arrival into meaningful categories:
- 0–30 days → Short Lead
- 31–90 days → Medium Lead
- More than 90 days → Long Lead

Business Meaning: Represents how early the guest made the booking before the arrival date.

ML Relevance: Booking lead time can capture different booking behaviors and may provide useful information for predicting cancellation and demand patterns.

Leakage Risk: Low, because lead time is available from the booking information.

Retain or Remove: Retain, because the categorical version makes lead-time patterns easier for an ML model to capture.

In [7]:
df["Booking_Lead_Category"] = pd.cut(
    df["lead_time"],
    bins=[-1, 30, 90, np.inf],
    labels=["Short Lead", "Medium Lead", "Long Lead"]
)

df[
    [
        "lead_time",
        "Booking_Lead_Category"
    ]
].head()

   lead_time Booking_Lead_Category
0        342             Long Lead
1        737             Long Lead
2          7            Short Lead
3         13            Short Lead
4         14            Short Lead

### Observation

The continuous `lead_time` feature has been converted into three meaningful booking categories.

The categories are:
- Short Lead → 0–30 days
- Medium Lead → 31–90 days
- Long Lead → More than 90 days

### Code Explanation

- `pd.cut()` divides the numerical `lead_time` values into defined intervals.
- The `bins` define the boundaries for each category.
- `labels` assign meaningful names to the categories.
- The feature is retained because it represents different booking behaviors in an easy-to-understand form.

### Feature 7: Guests_Per_Night

Feature Name: Guests_Per_Night

Source Columns: Total_Guests, Total_Stay_Nights

Logic: Divide the total number of guests by the total number of stay nights. Zero stay nights are handled to avoid division by zero.

Business Meaning: Represents the average number of guests associated with each night of the booking.

ML Relevance: Helps describe booking size relative to stay duration and can provide additional information about booking patterns.

Leakage Risk: Low, because the feature uses booking-time information.

Retain or Remove: Retain, because it combines guest count and stay duration into a meaningful hospitality feature.

In [8]:
df["Guests_Per_Night"] = np.where(
    df["Total_Stay_Nights"] > 0,
    df["Total_Guests"] / df["Total_Stay_Nights"],
    0
)

df[
    [
        "Total_Guests",
        "Total_Stay_Nights",
        "Guests_Per_Night"
    ]
].head()

   Total_Guests  Total_Stay_Nights  Guests_Per_Night
0           2.0                  0               0.0
1           2.0                  0               0.0
2           1.0                  1               1.0
3           1.0                  1               1.0
4           2.0                  2               1.0

### Observation

The `Guests_Per_Night` feature represents the number of guests relative to the total duration of the booking.

### Code Explanation

- `Total_Guests` provides the total number of guests.
- `Total_Stay_Nights` provides the total stay duration.
- The values are divided to create `Guests_Per_Night`.
- `np.where()` prevents division by zero when the stay duration is 0.
- The feature is retained because it combines two important hotel booking characteristics into one useful feature.

### Feature 8: ADR_Per_Guest

Feature Name: ADR_Per_Guest

Source Columns: adr, Total_Guests

Logic: Divide the Average Daily Rate (ADR) by the total number of guests. Zero guest counts are handled to avoid division by zero.

Business Meaning: Represents the average daily room rate relative to the number of guests in the booking.

ML Relevance: Helps capture the pricing level of a booking in relation to its guest count and can provide useful information for predicting booking behavior.

Leakage Risk: Low, provided ADR and guest count are available at the time of prediction.

Retain or Remove: Retain, because it provides a useful price-to-guest relationship.

In [9]:
df["ADR_Per_Guest"] = np.where(
    df["Total_Guests"] > 0,
    df["adr"] / df["Total_Guests"],
    0
)

df[
    [
        "adr",
        "Total_Guests",
        "ADR_Per_Guest"
    ]
].head()

    adr  Total_Guests  ADR_Per_Guest
0   0.0           2.0            0.0
1   0.0           2.0            0.0
2  75.0           1.0           75.0
3  75.0           1.0           75.0
4  98.0           2.0           49.0

### Observation

The `ADR_Per_Guest` feature represents the Average Daily Rate relative to the number of guests in the booking.

### Code Explanation

- `adr` represents the Average Daily Rate.
- `Total_Guests` represents the total number of guests.
- Dividing ADR by the total guest count creates `ADR_Per_Guest`.
- `np.where()` prevents division by zero when there are no guests.
- The feature is retained because it adds a useful pricing perspective based on guest count.

### Feature 9: Estimated_Stay_Revenue

Feature Name: Estimated_Stay_Revenue

Source Columns: adr, Total_Stay_Nights

Logic: Multiply the Average Daily Rate (ADR) by the total number of stay nights.

Business Meaning: Provides an estimated room revenue for the complete stay based on the daily rate and planned stay duration.

ML Relevance: Helps represent the approximate monetary value of a booking and can provide useful information for predicting booking behavior.

Leakage Risk: Low, provided ADR and planned stay duration are available at the time of prediction.

Retain or Remove: Retain, because it combines pricing and stay duration into a meaningful business feature.

In [10]:
df["Estimated_Stay_Revenue"] = (
    df["adr"] * df["Total_Stay_Nights"]
)

df[
    [
        "adr",
        "Total_Stay_Nights",
        "Estimated_Stay_Revenue"
    ]
].head()

    adr  Total_Stay_Nights  Estimated_Stay_Revenue
0   0.0                  0                     0.0
1   0.0                  0                     0.0
2  75.0                  1                    75.0
3  75.0                  1                    75.0
4  98.0                  2                   196.0

### Observation

The `Estimated_Stay_Revenue` feature represents the approximate room revenue for the planned hotel stay.

### Code Explanation

- `adr` represents the Average Daily Rate.
- `Total_Stay_Nights` represents the total planned stay duration.
- Multiplying these values gives an estimated stay revenue.
- The feature is retained because it combines price and stay duration into one useful hospitality feature.
- This is an estimate based on ADR and does not necessarily represent the final amount charged to the guest.

### Feature 10: Family_Booking

Feature Name: Family_Booking

Source Columns: children, babies

Logic: If the booking has one or more children or babies, assign 1; otherwise assign 0.

Business Meaning: Indicates whether the booking includes children or babies.

ML Relevance: Family bookings may have different booking patterns and requirements compared with bookings containing only adults. This can provide useful information for understanding booking behavior.

Leakage Risk: Low, because the guest composition is available in the booking information.

Retain or Remove: Retain, because it represents a meaningful guest-type characteristic.

In [11]:
df["Family_Booking"] = (
    (df["children"] > 0) |
    (df["babies"] > 0)
).astype(int)

df[
    [
        "children",
        "babies",
        "Family_Booking"
    ]
].head()

   children  babies  Family_Booking
0       0.0       0               0
1       0.0       0               0
2       0.0       0               0
3       0.0       0               0
4       0.0       0               0

### Observation

The `Family_Booking` feature identifies whether a booking includes children or babies.

The feature contains:
- 1 → Booking includes children or babies
- 0 → Booking does not include children or babies

### Code Explanation

- `children > 0` checks whether children are included in the booking.
- `babies > 0` checks whether babies are included.
- The `|` operator combines both conditions.
- `.astype(int)` converts the result into 1 and 0.
- The feature is retained because family-related booking information can represent different hospitality booking patterns.

### Feature 11: High_Demand_Period

Feature Name: High_Demand_Period

Source Columns: arrival_date_month

Logic: Group the arrival months into a simple seasonal indicator. Months commonly associated with higher booking activity are marked as 1, and the remaining months are marked as 0.

Business Meaning: Represents whether the booking falls within a potentially high-demand seasonal period.

ML Relevance: Seasonal booking patterns can help a model capture changes in hotel demand across different periods of the year.

Leakage Risk: Low, because the arrival month is known at the time of booking.

Retain or Remove: Retain, because seasonality is an important factor in the hospitality domain.

In [12]:
high_demand_months = [
    "July",
    "August",
    "June",
    "September"
]

df["High_Demand_Period"] = (
    df["arrival_date_month"]
    .isin(high_demand_months)
    .astype(int)
)

df[
    [
        "arrival_date_month",
        "High_Demand_Period"
    ]
].head()

  arrival_date_month  High_Demand_Period
0               July                   1
1               July                   1
2               July                   1
3               July                   1
4               July                   1

### Observation

The `High_Demand_Period` feature identifies bookings that fall within selected seasonal months.

The feature contains:
- 1 → Booking falls within the selected high-demand period
- 0 → Booking falls outside the selected period

### Code Explanation

- `high_demand_months` contains the selected months.
- `.isin()` checks whether each booking's arrival month belongs to this group.
- `.astype(int)` converts the result into 1 and 0.
- The feature is retained because arrival season can represent important demand patterns in hotel bookings.

Note: The selected months are a domain-based example, not a target-derived measure of actual demand.

### Feature 12: Repeat_Guest_Indicator

Feature Name: Repeat_Guest_Indicator

Source Columns: No suitable guest identifier is available in the dataset.

Logic: A true repeat-guest indicator would require a customer or guest ID to identify whether the same guest has made previous bookings.

Business Meaning: Indicates whether a guest has previously booked the hotel.

ML Relevance: Repeat-guest behavior can be useful for understanding customer loyalty and booking patterns.

Leakage Risk: Cannot be evaluated reliably without a guest identifier and historical booking information.

Retain or Remove: Remove / Not Created, because the Hotel Bookings dataset does not contain a reliable customer identifier.

In [13]:
customer_id_columns = [
    col for col in df.columns
    if "customer" in col.lower() or "guest_id" in col.lower()
]

customer_id_columns

['customer_type']

### Observation

No suitable customer or guest identifier is available for creating a reliable `Repeat_Guest_Indicator`.

### Code Explanation

- The code searches the dataset columns for possible customer or guest identifiers.
- Without a unique guest identifier, we cannot determine whether two bookings belong to the same guest.
- Therefore, this feature is not created to avoid making an unsupported assumption.

### Domain Learning

Some useful business features require information that is not available in the dataset. In such cases, the correct approach is to document the limitation rather than create an unreliable feature.

### Feature 13: Booking_Value_Category

Feature Name: Booking_Value_Category

Source Columns: Estimated_Stay_Revenue

Logic: Group the estimated stay revenue into three categories:
- Low Value
- Medium Value
- High Value

Business Meaning: Represents the approximate monetary value of the hotel booking.

ML Relevance: Helps distinguish bookings based on their estimated value and can provide useful information for understanding booking behavior.

Leakage Risk: Low, provided the ADR and planned stay duration are available at the time of prediction.

Retain or Remove: Retain, because booking value is a meaningful hospitality-domain characteristic.

In [14]:
df["Booking_Value_Category"] = pd.cut(
    df["Estimated_Stay_Revenue"],
    bins=[-np.inf, 500, 1500, np.inf],
    labels=["Low Value", "Medium Value", "High Value"]
)

df[
    [
        "Estimated_Stay_Revenue",
        "Booking_Value_Category"
    ]
].head()

   Estimated_Stay_Revenue Booking_Value_Category
0                     0.0              Low Value
1                     0.0              Low Value
2                    75.0              Low Value
3                    75.0              Low Value
4                   196.0              Low Value

### Observation

The `Estimated_Stay_Revenue` feature has been converted into three meaningful booking-value categories.

The categories are:
- Low Value → Up to 500
- Medium Value → 501–1500
- High Value → More than 1500

### Code Explanation

- `pd.cut()` divides the estimated revenue into defined ranges.
- `bins` specify the boundaries of the categories.
- `labels` assign meaningful business names.
- The feature is retained because booking value can help represent the financial importance of each reservation.

### Feature 14: Seasonal_Booking

Feature Name: Seasonal_Booking

Source Columns: arrival_date_month

Logic: Convert the arrival month into a seasonal category:
- December, January, February → Winter
- March, April, May → Spring
- June, July, August → Summer
- September, October, November → Autumn

Business Meaning: Represents the season in which the guest is scheduled to arrive.

ML Relevance: Seasonal patterns can influence hotel demand, booking behavior, and pricing patterns.

Leakage Risk: Low, because the arrival month is known at the time of booking.

Retain or Remove: Retain, because seasonality is a meaningful factor in the hospitality domain.

In [15]:
season_map = {
    "December": "Winter",
    "January": "Winter",
    "February": "Winter",
    "March": "Spring",
    "April": "Spring",
    "May": "Spring",
    "June": "Summer",
    "July": "Summer",
    "August": "Summer",
    "September": "Autumn",
    "October": "Autumn",
    "November": "Autumn"
}

df["Seasonal_Booking"] = df["arrival_date_month"].map(season_map)

df[
    [
        "arrival_date_month",
        "Seasonal_Booking"
    ]
].head()

  arrival_date_month Seasonal_Booking
0               July           Summer
1               July           Summer
2               July           Summer
3               July           Summer
4               July           Summer

### Observation

The `arrival_date_month` feature has been converted into four seasonal categories.

The categories are:
- Winter
- Spring
- Summer
- Autumn

### Code Explanation

- `season_map` defines the relationship between each month and its season.
- `.map()` converts the arrival month into the corresponding seasonal category.
- The feature is retained because seasonal information can help the model capture different hotel booking patterns throughout the year.

### Feature 15: Booking_Season

Feature Name: Booking_Season

Source Columns: arrival_date_month

Logic: Categorize the arrival month into a business-oriented season.

Business Meaning: Represents the seasonal period in which the guest is expected to arrive.

ML Relevance: Seasonal information can help the model identify differences in booking patterns, demand, and pricing across the year.

Leakage Risk: Low, because the arrival month is available from the booking information.

Retain or Remove: Retain, because seasonality is relevant to hotel booking behavior.

In [16]:
season_map = {
    "December": "Winter",
    "January": "Winter",
    "February": "Winter",
    "March": "Spring",
    "April": "Spring",
    "May": "Spring",
    "June": "Summer",
    "July": "Summer",
    "August": "Summer",
    "September": "Autumn",
    "October": "Autumn",
    "November": "Autumn"
}

df["Booking_Season"] = df["arrival_date_month"].map(season_map)

df[
    [
        "arrival_date_month",
        "Booking_Season"
    ]
].head()

  arrival_date_month Booking_Season
0               July         Summer
1               July         Summer
2               July         Summer
3               July         Summer
4               July         Summer

### Observation

The `arrival_date_month` column has been converted into a seasonal feature called `Booking_Season`.

This feature represents the expected arrival season of the booking.

### Code Explanation

- `season_map` maps each month to a corresponding season.
- `.map()` applies this mapping to the arrival month.
- The new feature is retained because seasonal patterns are meaningful in the hospitality domain.

### Feature 16: Special_Request_Rate

Feature Name: Special_Request_Rate

Source Columns: total_of_special_requests, Total_Stay_Nights

Logic: Divide the total number of special requests by the total number of stay nights. Zero stay nights are handled to avoid division by zero.

Business Meaning: Represents the frequency of special requests relative to the length of the guest's stay.

ML Relevance: Helps capture guest behavior more precisely than the total number of requests alone and may provide additional information for booking-related predictions.

Leakage Risk: Low, provided special requests and planned stay duration are available at the time of prediction.

Retain or Remove: Retain, because it combines guest requests with stay duration into a meaningful hospitality feature.

In [17]:
df["Special_Request_Rate"] = np.where(
    df["Total_Stay_Nights"] > 0,
    df["Total_Special_Requests"] / df["Total_Stay_Nights"],
    0
)

df[
    [
        "Total_Special_Requests",
        "Total_Stay_Nights",
        "Special_Request_Rate"
    ]
].head()

   Total_Special_Requests  Total_Stay_Nights  Special_Request_Rate
0                       0                  0                   0.0
1                       0                  0                   0.0
2                       0                  1                   0.0
3                       0                  1                   0.0
4                       1                  2                   0.5

### Observation

The `Special_Request_Rate` feature represents the number of special requests relative to the total length of the stay.

### Code Explanation

- `Total_Special_Requests` represents the number of special requests.
- `Total_Stay_Nights` represents the planned stay duration.
- Dividing the two creates `Special_Request_Rate`.
- `np.where()` prevents division by zero.
- The feature is retained because it provides additional information about guest request behavior relative to stay duration.

### Feature 17: Guest_Composition

Feature Name: Guest_Composition

Source Columns: adults, children, babies

Logic: Categorize the booking based on the combination of adults, children, and babies.

Business Meaning: Represents the type of guest group associated with the booking.

ML Relevance: Different guest compositions may have different booking patterns and requirements. This feature can help the model capture those differences.

Leakage Risk: Low, because guest composition is available in the booking information.

Retain or Remove: Retain, because guest composition is meaningful in the hotel booking domain.

In [18]:
def get_guest_composition(row):
    if row["children"] > 0 or row["babies"] > 0:
        return "Family"
    elif row["adults"] == 1:
        return "Solo"
    else:
        return "Adults Only"

df["Guest_Composition"] = df.apply(
    get_guest_composition,
    axis=1
)

df[
    [
        "adults",
        "children",
        "babies",
        "Guest_Composition"
    ]
].head()

   adults  children  babies Guest_Composition
0       2       0.0       0       Adults Only
1       2       0.0       0       Adults Only
2       1       0.0       0              Solo
3       1       0.0       0              Solo
4       2       0.0       0       Adults Only

### Observation

The `Guest_Composition` feature categorizes bookings into meaningful guest groups:

- Family → Booking includes children or babies
- Solo → Booking has one adult and no children or babies
- Adults Only → Booking has multiple adults and no children or babies

### Code Explanation

- The function checks the number of adults, children, and babies.
- `apply()` applies the function to each booking.
- The resulting categories provide a higher-level representation of guest composition.
- The feature is retained because guest-group type is relevant to hotel booking behavior.